package com.nuist.pojo;

public class Class {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.cid
     *
     * @mbggenerated Tue Jun 27 14:05:39 CST 2023
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.cname
     *
     * @mbggenerated Tue Jun 27 14:05:39 CST 2023
     */
    private String cname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.cid
     *
     * @return the value of t_class.cid
     *
     * @mbggenerated Tue Jun 27 14:05:39 CST 2023
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.cid
     *
     * @param cid the value for t_class.cid
     *
     * @mbggenerated Tue Jun 27 14:05:39 CST 2023
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.cname
     *
     * @return the value of t_class.cname
     *
     * @mbggenerated Tue Jun 27 14:05:39 CST 2023
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.cname
     *
     * @param cname the value for t_class.cname
     *
     * @mbggenerated Tue Jun 27 14:05:39 CST 2023
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }
}